name: Build & Test Code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          make install
      - name: Format Python code (Black formatter)
        run: |
          make format
      - name: Sort Python imports (isort)
        run: |
          make isort src/
      - name: Lint (pylint)
        run: |
          make lint
      - name: Test (pytest)
        run: |
          make test
